blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/graphql-java-kickstart/graphql-java-servlet/discussions
    about: Anything you are not sure about? Ask the community in Discussions!
